name: "eks_tf_deploy"
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  Plan:
    uses: swapnil-dhawad/golang-k8s-demo/.github/workflows/aws_tf_plan.yml@main 
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  